DEFINITION


Computer vision is an interdisciplinary field that deals with how computers can be made to gain high-level understanding from digital images or videos.

Computer Vision is concerned with the theory behind artificial systems that extract information from images. The image data can take many forms, such as video sequences, views from multiple cameras, or multi-dimensional data from a medical scanner. As a technological discipline, computer vision seeks to apply its theories and models for the construction of computer vision systems.

Sub-domains of computer vision include scene reconstruction, event detection, video tracking, object recognition, 3D pose estimation, learning, indexing, motion estimation, and image restoration.

# Why To Study CV ?

In [ ]:
Manipulation in processing of imagery .
Extracting information of imagery .
        Building 3d representation.
        Motion Capturing.

In [ ]:
import cv2

# What is Colour Spaces ?

In [ ]:
#Opencv

In [ ]:
import cv2 
import numpy as np 
import matplotlib.pyplot as plt                        
#print image
img=cv2.imread("C:\\Users\\Rajat arya\\Downloads\\index.png")
plt.imshow(img)                                                     ## opencv stores BGR image by default
plt.show()

#printing color image of an image
img2 = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
plt.imshow(img2)                                                ## original image               ## Convert BGR to RGB image
plt.show()
#printing hsv image of an image
hsv_image = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)                   ## Convert BGR to HSV image 
plt.imshow(hsv_image)



IMAGE ROTATION

In [ ]:
import numpy as np 
import cv2 
import matplotlib.pyplot as plt 
%matplotlib inline 
image = cv2.imread("C:\\Users\\Rajat arya\\Downloads\\index.png") 
rows,cols = image.shape[:2] 
#(col/2,rows/2) is the center of rotation for the image 
# M is the cordinates of the center 
M = cv2.getRotationMatrix2D((cols/2,rows/2),180,1) 
dst = cv2.warpAffine(image,M,(cols,rows)) 
plt.imshow(dst)

In [ ]:
tracker=ask_tracker()
tracker_name=str(tracker).split()[0][1:]

#read video
cap=cv2.VideoCapture(0)

#read first frame
ret,frame=cap.read()

roi=cv2.selectROI(frame,False)

ret=tracker.init(frame,roi)

while True:
    frame,ret=cap.read()
    success,roi=tracker.update(frame)
    x,y,w,h=tuple(map(int,roi))
    
    if success:
        p1=x,y
        p2=(x+w ,y+h)
        cv2.rectangle(frame,p1,p2,(0,255,0),3)
    else:
        cv2.putText(frame,"Failure to Detect Tracling",(100,200),cv2.FONT_HERSHEY_SIMPLEX,1)
    cv2.putText(frame,tracker_name,(20,400),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),3)    
        
    cv2.imshow(tracker_name,frame)
    k=cv2.waitKey(1) and 0xff
    if k==27:
        break
    cap.release()
    cap.destroyAllWindows()
        
        
        
        


# OPTICAL FLOW CODING

Optical flow is the pattern of apparent motion of image objects between two consecutive frames caused by the movemement of object or camera. It is 2D vector field where each vector is a displacement vector showing the movement of points from first frame to second.

In [ ]:
import cv2

In [ ]:
img=cv2.imread("C:\\Users\\Rajat arya\\Downloads\\index.png")
print(img.shape)


In [ ]:
import cv2
 
# Black and White (gray scale)
 
img = cv2.imread ("C:\\Users\\Rajat arya\\Downloads\\index.png")
 
cv2.imshow("picture", img) 
 
cv2.waitKey(0)

# cv2.waitKey(2000)
 
cv2.destroyAllWindows()

In [ ]:
import cv2      # Resize image
 

 
img = cv2.imread ("C:\\Users\\Rajat arya\\Downloads\\index.png",1)
 
resized_image = cv2.resize(img, (650,500))
 
cv2.imshow("My_image", resized_image)
 
cv2.waitKey(0)
 
cv2.destroyAllWindows()

In [ ]:
print(resized_image.shape)

In [ ]:
Resized_image = cv2.resize(img, int(img.shape[1]/2), int(img.shape[0]/2)))

In [ ]:
import cv2      # Resize image
 
# Black and White (gray scale)
 
img = cv2.imread ("C:\\Users\\Rajat arya\\Downloads\\index.png",1)
 
resized_image = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))
 
cv2.imshow("My_image", resized_image)
 
cv2.waitKey(0)
 
cv2.destroyAllWindows()

In [ ]:
# face detection 

In [25]:
import cv2
 
# Create a CascadeClassifier Object
face_cascade = cv2.CascadeClassifier("C:\\Users\\Rajat arya\\Desktop\\haarcascade_frontalface_default.xml")
 
# Reading the image as it is
img = cv2.imread("C:\\Users\\Rajat arya\\Pictures\\Screenshots\\me.png")
 
# Reading the image as gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
 
# Search the co-ordintes of the image
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05,minNeighbors=5)
print(faces)
for x,y,w,h in faces:
    #cv2.rectangle(image, start_point, end_point, color, thickness)
    img = cv2.rectangle(img, (x,y), (x+w,y+h),(255,20,120),10)
 
resized = cv2.resize(img, (int(img.shape[1]/4),int(img.shape[0]/4)))
 
cv2.imshow("Gray", resized)
 
cv2.waitKey(0)
 
cv2.destroyAllWindows()

[[763 153 563 563]]


In [ ]:
print(x,y)

In [ ]:
print(x+w,y+h)

In [ ]:
print(img.shape)

In [ ]:
import cv2 
import numpy as np 
import matplotlib.pyplot as plt                        
#print image
img=cv2.imread("C:\\Users\\Rajat arya\\Downloads\\index.png")
plt.imshow(img)                                                     ## opencv stores BGR image by default
plt.show()


In [ ]:
img2 = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
plt.imshow(img2)                                                ## original image               ## Convert BGR to RGB image
plt.show()
#printing hsv image of an image
hsv_image = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)                   ## Convert BGR to HSV image 
plt.imshow(hsv_image)

In [ ]:
import cv2
import time
video = cv2.VideoCapture(0)
video.release()

In [ ]:
import cv2
import time
video = cv2.VideoCapture(0)
check,frame =video.read()
cv2.imshow("video",frame)
cv2.waitKey(0)

video.release()
cv2.destroyAllWindows()

In [28]:
import cv2
 
# Create a CascadeClassifier Object
eye_cascade = cv2.CascadeClassifier("C:\\Users\\Rajat arya\\Desktop\\haarcascade_eye.xml")
 
# Reading the image as it is
img = cv2.imread("C:\\Users\\Rajat arya\\Pictures\\Screenshots\\me.png")
 
# Reading the image as gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
 
# Search the co-ordintes of the image
Eyes = eye_cascade.detectMultiScale(gray_img, scaleFactor = 1.05,minNeighbors=5)
#print(faces)
for x,y,w,h in Eyes:
    #cv2.rectangle(image, start_point, end_point, color, thickness)
    img = cv2.rectangle(img, (x,y), (x+w,y+h),(255,20,120),10)
 
resized = cv2.resize(img, (int(img.shape[1]/4),int(img.shape[0]/4)))
 
cv2.imshow("Gray", resized)
 
cv2.waitKey(0)
 
cv2.destroyAllWindows()

In [36]:
import numpy as np    #modified code for faces and eyes detection
import cv2
face_cascade = cv2.CascadeClassifier("C:\\Users\\Rajat arya\\Desktop\\haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("C:\\Users\\Rajat arya\\Desktop\\haarcascade_eye.xml")
 
img = cv2.imread("C:\\Users\\Rajat arya\\Pictures\\Screenshots\\Screenshot (209).png")
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
     cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),10)
     roi_gray = gray[y:y+h, x:x+w]
     roi_color = img[y:y+h, x:x+w]
     eyes = eye_cascade.detectMultiScale(roi_gray)
     for (ex,ey,ew,eh) in eyes:
         cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),5)
resized = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
        
cv2.imshow("image",resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
import cv2
import time
video = cv2.VideoCapture(0)
video.release()

In [46]:
import cv2
video = cv2.VideoCapture(0)
check,frame =video.read()   
print(check)
print(frame)
cv2.imshow("video",frame)
cv2.waitKey(0) 

video.release()
cv2.destroyAllWindows()

True
[[[226 229 213]
  [226 229 213]
  [231 230 214]
  ...
  [143 163 157]
  [146 166 161]
  [153 173 168]]

 [[226 229 213]
  [226 229 213]
  [230 229 213]
  ...
  [144 164 158]
  [147 168 162]
  [153 173 168]]

 [[228 228 215]
  [228 228 215]
  [229 226 215]
  ...
  [143 165 153]
  [151 169 157]
  [158 176 164]]

 ...

 [[157 148 134]
  [161 152 137]
  [169 155 136]
  ...
  [ 61  85  81]
  [ 51  76  72]
  [ 50  74  71]]

 [[155 144 135]
  [158 148 138]
  [161 150 140]
  ...
  [ 70  84  82]
  [ 58  76  76]
  [ 57  75  74]]

 [[155 144 135]
  [156 146 136]
  [159 149 139]
  ...
  [ 71  86  83]
  [ 58  76  76]
  [ 57  75  74]]]


In [23]:
import cv2

#1 Creating a video object 
video = cv2.VideoCapture(0)

#3 Creating a frame object
check,frame =video.read()

cv2.imshow("video",frame)
cv2.waitKey(0)

#2 shutdown 
video.release()
cv2.destroyAllWindows()

In [6]:
import cv2

video =cv2.VideoCapture(0)
a=0
while True:
    a=a+1
    check,frame=video.read()
    cv2.imshow("capturing",frame)
    k=cv2.waitKey(1)
    if k==ord('q'):
        break

video.release()
cv2.destroyAllWindows()