In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,7,27,36]] , np.int64)

In [3]:
myarr[0,1]

7

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0,1] = 43

In [7]:
myarr

array([[ 3, 43, 27, 36]], dtype=int64)

# array creation: conversion from other python structure

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1,5,4)

In [22]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        2.22522597e-306, 1.33511969e-306, 1.24610383e-306],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306, 8.45590539e-307],
       [6.23054972e-307, 2.22522597e-306, 1.06810268e-306,
        6.23052935e-307, 8.45602762e-307, 1.33511969e-306],
       [1.69118787e-306, 1.42418172e-306, 1.37961641e-306,
        1.27946076e-307, 8.45610231e-307, 0.00000000e+000]])